field_menu.settings:
  type: mapping
  label: 'Field menu settings'
  mapping:
    menu_type_checkbox:
      type: sequence
      label: 'Available menus'
      orderby: key
      sequence:
        type: system.menu.[%id]
        label: 'Menu'
    menu_type_checkbox_negate:
      type: boolean
      label: 'Negate the condition'

field.storage_settings.field_menu:
  type: mapping
  label: 'Menu field settings'

field.field_settings.field_menu:
  type: mapping
  label: 'Menu field settings'
  mapping:
    menu_type_checkbox:
      type: sequence
      label: 'Available menus'
      orderby: key
      sequence:
        type: system.menu.[%key]
        label: 'Menus'
    menu_type_checkbox_negate:
      type: boolean
      label: 'Negate the condition'

field.value.field_menu:
  type: mapping
  label: 'Default value'
  mapping:
    menu:
      type: text
      label: Selected menu
    options:
      type: text
      label: Menu options
