field_menu.settings:
  type: mapping
  label: 'Field menu settings'
  mapping:
    menu_type_checkbox:
      type: sequence
      label: 'Available menus'
      orderby: key
      sequence:
        type: system.menu.[%id]
        label: 'Menu'
    menu_type_checkbox_negate:
      type: boolean
      label: 'Negate the condition'

field.storage_settings.field_menu:
  type: mapping
  label: 'Menu field settings'

field.field_settings.field_menu:
  type: mapping
  label: 'Field menu settings'
  mapping:
    menu_type_checkbox:
      type: sequence
      label: 'Available menus'
      orderby: key
      sequence:
        type: system.menu.[%key]
        label: 'Menus'
    menu_type_checkbox_negate:
      type: boolean
      label: 'Negate the condition'

field.value.field_menu:
  type: mapping
  label: 'Default value'
  mapping:
    title:
      type: string
      label: 'Menu title'
    menu:
      type: string
      label: 'Selected menu'
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Depth'
    expand_all_items:
      type: boolean
      label: 'Expand all items'
    follow:
      type: boolean
      label: 'Follow'
    follow_parent:
      type: string
      label: 'Follow option'
    parent:
      type: string
      label: 'Parent menu link'
    render_parent:
      type: boolean
      label: 'Render parent menu link'
